using System;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.IO;
using System.Reflection.Emit;
using Microsoft.SqlServer.Server;
using MIS333K_FinalProject.DAL;
using MIS333K_FinalProject.Models;
using Mono.TextTemplating;
using static System.Reflection.Metadata.BlobBuilder;
using Microsoft.EntityFrameworkCore;

namespace MIS333K_FinalProject.Seeding
{
    public class SeedProperties
    {
        public static void SeedOneProperty(AppDbContext db)
        {
            using (var transaction = db.Database.BeginTransaction())
            {
                try
                {
                    db.Database.ExecuteSqlRaw("SET IDENTITY_INSERT Properties ON");

                    // Fetch the Host
                    var host = db.Users.FirstOrDefault(g => g.Email == "tanner@utexas.edu");
                    if (host == null)
                    {
                        throw new Exception("Host with email 'tanner@utexas.edu' not found in the database.");
                    }

                    // Add the property
                    db.Properties.Add(new Models.Property
                    {
                        PropertyId = 3183,
                        ZipCode = "56713",
                        State = StateAbbr.TX,
                        Street = "690 Christina Park",
                        City = "Toddburgh",
                        WeekendPrice = 157.96m,
                        WeekdayPrice = 188.53m,
                        PetsAllowed = false,
                        FreeParking = false,
                        CleaningFee = 6.69m,
                        Bedrooms = 3,
                        Bathrooms = 5,
                        GuestsAllowed = 1,
                        PropertyStatus = PropStatus.Approved,
                        Host = host,
                        //HostEmail = host.Email, // Explicitly set HostEmail
                        Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin")
                    });

                    db.SaveChanges();
                    db.Database.ExecuteSqlRaw("SET IDENTITY_INSERT Properties OFF");
                    transaction.Commit();

                    Console.WriteLine("Successfully seeded property with PropertyId = 3183.");
                }
                catch (Exception ex)
                {
                    transaction.Rollback();
                    Console.WriteLine("Error seeding property: " + ex.Message);
                    throw;
                }
            }
        }




        public static void SeedAllProperties(AppDbContext db)
        {
            // Define a list of categories to seed
            List<Models.Property> Properties = new List<Models.Property>
            {
                new Models.Property { PropertyId = 3001, ZipCode = "72227", State = StateAbbr.PA, Street = "8714 Mann Plaza", City = "Lisaside", WeekendPrice = 171.57m, WeekdayPrice = 152.68m, PetsAllowed = false, FreeParking = false, CleaningFee = 8.88m, Bedrooms = 5, Bathrooms = 6, GuestsAllowed = 9, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "gonzalez@aol.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3002, ZipCode = "05565", State = StateAbbr.FL, Street = "96593 White View Apt. 094", City = "Jonesberg", WeekendPrice = 148.15m, WeekdayPrice = 120.81m, PetsAllowed = false, FreeParking = true, CleaningFee = 8.02m, Bedrooms = 7, Bathrooms = 8, GuestsAllowed = 8, MinNightsForDiscount = 4, DiscountRate = 0.14m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "gonzalez@aol.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3003, ZipCode = "80819", State = StateAbbr.MD, Street = "848 Melissa Springs Suite 947", City = "Kellerstad", WeekendPrice = 132.99m, WeekdayPrice = 127.96m, PetsAllowed = false, FreeParking = true, CleaningFee = 13.37m, Bedrooms = 5, Bathrooms = 7, GuestsAllowed = 8, PropertyStatus = PropStatus.Unapproved, Host = db.Users.FirstOrDefault(g => g.Email == "rankin@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Condo") },
                new Models.Property { PropertyId = 3004, ZipCode = "79428", State = StateAbbr.ND, Street = "30413 Norton Isle Suite 012", City = "North Lisa", WeekendPrice = 185.35m, WeekdayPrice = 80.20m, PetsAllowed = true, FreeParking = true, CleaningFee = 5.57m, Bedrooms = 1, Bathrooms = 3, GuestsAllowed = 14, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "rankin@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Hotel") },
                new Models.Property { PropertyId = 3005, ZipCode = "63315", State = StateAbbr.DE, Street = "39916 Mitchell Crescent", City = "New Andrewburgh", WeekendPrice = 100.37m, WeekdayPrice = 170.25m, PetsAllowed = true, FreeParking = true, CleaningFee = 18.64m, Bedrooms = 2, Bathrooms = 3, GuestsAllowed = 12, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "loter@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3006, ZipCode = "24135", State = StateAbbr.NE, Street = "086 Mary Cliff", City = "North Deborah", WeekendPrice = 162.60m, WeekdayPrice = 220.24m, PetsAllowed = false, FreeParking = true, CleaningFee = 10.83m, Bedrooms = 7, Bathrooms = 9, GuestsAllowed = 2, MinNightsForDiscount = 10, DiscountRate = 0.24m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "rice@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3007, ZipCode = "58475", State = StateAbbr.PA, Street = "91634 Strong Mountains Apt. 302", City = "West Alyssa", WeekendPrice = 204.87m, WeekdayPrice = 213.37m, PetsAllowed = true, FreeParking = true, CleaningFee = 25.04m, Bedrooms = 1, Bathrooms = 2, GuestsAllowed = 9, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "rice@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3008, ZipCode = "10865", State = StateAbbr.WA, Street = "6984 Price Shoals", City = "Erictown", WeekendPrice = 140.89m, WeekdayPrice = 159.69m, PetsAllowed = true, FreeParking = true, CleaningFee = 27.13m, Bedrooms = 2, Bathrooms = 3, GuestsAllowed = 8, MinNightsForDiscount = 7, DiscountRate = 0.05m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "tanner@utexas.edu"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3009, ZipCode = "51359", State = StateAbbr.ME, Street = "423 Bell Heights", City = "Brittanyberg", WeekendPrice = 295.39m, WeekdayPrice = 200.73m, PetsAllowed = false, FreeParking = true, CleaningFee = 14.91m, Bedrooms = 3, Bathrooms = 3, GuestsAllowed = 4, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "rice@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3010, ZipCode = "87296", State = StateAbbr.WI, Street = "93523 Dana Lane", City = "Johnsonshire", WeekendPrice = 110.80m, WeekdayPrice = 170.39m, PetsAllowed = false, FreeParking = false, CleaningFee = 8.67m, Bedrooms = 6, Bathrooms = 6, GuestsAllowed = 3, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "ingram@gmail.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3011, ZipCode = "07035", State = StateAbbr.NH, Street = "1427 Odonnell Rapids", City = "North Troyport", WeekendPrice = 126.29m, WeekdayPrice = 217.15m, PetsAllowed = true, FreeParking = true, CleaningFee = 26.48m, Bedrooms = 3, Bathrooms = 3, GuestsAllowed = 14, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "jacobs@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3012, ZipCode = "37198", State = StateAbbr.ME, Street = "81206 Stewart Forest Apt. 089", City = "East Davidborough", WeekendPrice = 293.26m, WeekdayPrice = 205.21m, PetsAllowed = true, FreeParking = false, CleaningFee = 28.74m, Bedrooms = 3, Bathrooms = 5, GuestsAllowed = 8, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "martinez@aol.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3013, ZipCode = "85034", State = StateAbbr.SD, Street = "76104 Marsh Crescent", City = "Dennishaven", WeekendPrice = 126.99m, WeekdayPrice = 123.13m, PetsAllowed = false, FreeParking = true, CleaningFee = 18.73m, Bedrooms = 7, Bathrooms = 7, GuestsAllowed = 4, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "chung@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3014, ZipCode = "60619", State = StateAbbr.SD, Street = "0003 Grant Lakes", City = "Port Karafort", WeekendPrice = 188.81m, WeekdayPrice = 89.19m, PetsAllowed = false, FreeParking = true, CleaningFee = 11.98m, Bedrooms = 3, Bathrooms = 5, GuestsAllowed = 14, PropertyStatus = PropStatus.Unapproved, Host = db.Users.FirstOrDefault(g => g.Email == "jacobs@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3015, ZipCode = "21978", State = StateAbbr.KY, Street = "236 Smith Drive Suite 555", City = "West Kimberlyton", WeekendPrice = 132.96m, WeekdayPrice = 198.30m, PetsAllowed = true, FreeParking = true, CleaningFee = 13.96m, Bedrooms = 1, Bathrooms = 3, GuestsAllowed = 11, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "jacobs@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Condo") },
                new Models.Property { PropertyId = 3016, ZipCode = "14742", State = StateAbbr.MT, Street = "6824 Timothy Garden Apt. 428", City = "West Richardmouth", WeekendPrice = 297.31m, WeekdayPrice = 181.50m, PetsAllowed = false, FreeParking = false, CleaningFee = 10.09m, Bedrooms = 6, Bathrooms = 6, GuestsAllowed = 10, MinNightsForDiscount = 22, DiscountRate = 0.13m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "rankin@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3017, ZipCode = "11894", State = StateAbbr.SC, Street = "5517 Holly Meadow Apt. 452", City = "Lake Anne", WeekendPrice = 139.22m, WeekdayPrice = 134.09m, PetsAllowed = false, FreeParking = false, CleaningFee = 9.75m, Bedrooms = 1, Bathrooms = 3, GuestsAllowed = 1, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "gonzalez@aol.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3018, ZipCode = "28976", State = StateAbbr.TX, Street = "30601 Hawkins Highway", City = "Morashire", WeekendPrice = 160.61m, WeekdayPrice = 187.65m, PetsAllowed = false, FreeParking = false, CleaningFee = 7.50m, Bedrooms = 6, Bathrooms = 5, GuestsAllowed = 9, MinNightsForDiscount = 30, DiscountRate = 0.11m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "martinez@aol.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3019, ZipCode = "28798", State = StateAbbr.AZ, Street = "49263 Wilson View Apt. 873", City = "South Raymondborough", WeekendPrice = 133.25m, WeekdayPrice = 206.95m, PetsAllowed = false, FreeParking = false, CleaningFee = 14.04m, Bedrooms = 1, Bathrooms = 3, GuestsAllowed = 5, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "loter@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3020, ZipCode = "68819", State = StateAbbr.NE, Street = "76582 Vanessa Oval", City = "New Richard", WeekendPrice = 242.89m, WeekdayPrice = 99.54m, PetsAllowed = true, FreeParking = false, CleaningFee = 6.61m, Bedrooms = 5, Bathrooms = 4, GuestsAllowed = 12, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "chung@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3021, ZipCode = "50177", State = StateAbbr.FL, Street = "7389 Alec Squares Suite 508", City = "Port Jonathan", Host = db.Users.FirstOrDefault(g => g.Email == "loter@yahoo.com"), WeekendPrice = 165.32m, WeekdayPrice = 112.62m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Condo"), PetsAllowed = true, FreeParking = true, CleaningFee = 24.26m, Bedrooms = 7, Bathrooms = 7, GuestsAllowed = 12, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3022, ZipCode = "66355", State = StateAbbr.NC, Street = "18013 Billy Bridge Suite 522", City = "Schmitthaven", Host = db.Users.FirstOrDefault(g => g.Email == "martinez@aol.com"), WeekendPrice = 119.02m, WeekdayPrice = 199.21m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Hotel"), PetsAllowed = false, FreeParking = true, CleaningFee = 11.63m, Bedrooms = 3, Bathrooms = 4, GuestsAllowed = 2, MinNightsForDiscount = 21, DiscountRate = 0.13m, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3023, ZipCode = "51431", State = StateAbbr.NJ, Street = "891 Bullock Ford", City = "Amandachester", Host = db.Users.FirstOrDefault(g => g.Email == "gonzalez@aol.com"), WeekendPrice = 244.93m, WeekdayPrice = 179.05m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House"), PetsAllowed = false, FreeParking = false, CleaningFee = 21.78m, Bedrooms = 5, Bathrooms = 6, GuestsAllowed = 11, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3024, ZipCode = "50853", State = StateAbbr.MT, Street = "02489 Cook Park", City = "Sherriport", Host = db.Users.FirstOrDefault(g => g.Email == "chung@yahoo.com"), WeekendPrice = 227.35m, WeekdayPrice = 207.24m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin"), PetsAllowed = false, FreeParking = true, CleaningFee = 5.5m, Bedrooms = 4, Bathrooms = 3, GuestsAllowed = 6, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3025, ZipCode = "20341", State = StateAbbr.UT, Street = "23450 Timothy Divide", City = "Wuland", Host = db.Users.FirstOrDefault(g => g.Email == "jacobs@yahoo.com"), WeekendPrice = 278.36m, WeekdayPrice = 116.01m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House"), PetsAllowed = false, FreeParking = true, CleaningFee = 24.73m, Bedrooms = 3, Bathrooms = 4, GuestsAllowed = 11, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3026, ZipCode = "85565", State = StateAbbr.OH, Street = "0976 Williams Mountains Apt. 009", City = "Lake Mario", Host = db.Users.FirstOrDefault(g => g.Email == "chung@yahoo.com"), WeekendPrice = 293.42m, WeekdayPrice = 225.14m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment"), PetsAllowed = true, FreeParking = true, CleaningFee = 10.42m, Bedrooms = 6, Bathrooms = 7, GuestsAllowed = 7, MinNightsForDiscount = 28, DiscountRate = 0.06m, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3027, ZipCode = "51884", State = StateAbbr.WY, Street = "1097 Santos Springs Suite 264", City = "New Michelleborough", Host = db.Users.FirstOrDefault(g => g.Email == "loter@yahoo.com"), WeekendPrice = 126.45m, WeekdayPrice = 70.24m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Hotel"), PetsAllowed = false, FreeParking = true, CleaningFee = 18.69m, Bedrooms = 2, Bathrooms = 2, GuestsAllowed = 4, MinNightsForDiscount = 3, DiscountRate = 0.08m, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3028, ZipCode = "66353", State = StateAbbr.SC, Street = "5100 Scott Burg", City = "East Clayton", Host = db.Users.FirstOrDefault(g => g.Email == "morales@aol.com"), WeekendPrice = 224.07m, WeekdayPrice = 186.38m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin"), PetsAllowed = false, FreeParking = false, CleaningFee = 28.24m, Bedrooms = 4, Bathrooms = 3, GuestsAllowed = 3, MinNightsForDiscount = 20, DiscountRate = 0.06m, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3029, ZipCode = "57004", State = StateAbbr.NV, Street = "412 Snow Manors Apt. 161", City = "South Kimtown", Host = db.Users.FirstOrDefault(g => g.Email == "morales@aol.com"), WeekendPrice = 120.93m, WeekdayPrice = 112.47m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment"), PetsAllowed = true, FreeParking = false, CleaningFee = 23.28m, Bedrooms = 5, Bathrooms = 7, GuestsAllowed = 9, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3030, ZipCode = "48447", State = StateAbbr.IN, Street = "5415 David Square", City = "West Michaeltown", Host = db.Users.FirstOrDefault(g => g.Email == "gonzalez@aol.com"), WeekendPrice = 100.02m, WeekdayPrice = 214.81m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House"), PetsAllowed = false, FreeParking = false, CleaningFee = 17.78m, Bedrooms = 7, Bathrooms = 9, GuestsAllowed = 1, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3031, ZipCode = "62982", State = StateAbbr.DE, Street = "03104 Norris Rapids", City = "Port Donald", Host = db.Users.FirstOrDefault(g => g.Email == "loter@yahoo.com"), WeekendPrice = 161.6m, WeekdayPrice = 159.87m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House"), PetsAllowed = true, FreeParking = true, CleaningFee = 10.34m, Bedrooms = 1, Bathrooms = 2, GuestsAllowed = 11, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3032, ZipCode = "16915", State = StateAbbr.FL, Street = "03557 Phillips Wells Suite 291", City = "New Beverlyburgh", Host = db.Users.FirstOrDefault(g => g.Email == "loter@yahoo.com"), WeekendPrice = 203.6m, WeekdayPrice = 70.55m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Condo"), PetsAllowed = false, FreeParking = true, CleaningFee = 5.09m, Bedrooms = 7, Bathrooms = 6, GuestsAllowed = 4, MinNightsForDiscount = 30, DiscountRate = 0.23m, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3033, ZipCode = "39742", State = StateAbbr.MT, Street = "332 Watson Shore Apt. 290", City = "Millerland", Host = db.Users.FirstOrDefault(g => g.Email == "rice@yahoo.com"), WeekendPrice = 299.34m, WeekdayPrice = 176.37m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment"), PetsAllowed = false, FreeParking = true, CleaningFee = 17.38m, Bedrooms = 3, Bathrooms = 3, GuestsAllowed = 2, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3034, ZipCode = "54060", State = StateAbbr.MS, Street = "645 John Roads", City = "Danahaven", Host = db.Users.FirstOrDefault(g => g.Email == "morales@aol.com"), WeekendPrice = 229.98m, WeekdayPrice = 172.83m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House"), PetsAllowed = false, FreeParking = false, CleaningFee = 23.55m, Bedrooms = 7, Bathrooms = 6, GuestsAllowed = 14, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3035, ZipCode = "55774", State = StateAbbr.HI, Street = "3547 Stephanie Underpass Apt. 418", City = "Port Jacqueline", Host = db.Users.FirstOrDefault(g => g.Email == "tanner@utexas.edu"), WeekendPrice = 143.71m, WeekdayPrice = 177.08m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment"), PetsAllowed = true, FreeParking = true, CleaningFee = 19.21m, Bedrooms = 1, Bathrooms = 1, GuestsAllowed = 5, MinNightsForDiscount = 42, DiscountRate = 0.13m, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3036, ZipCode = "59363", State = StateAbbr.UT, Street = "5825 Welch Corners", City = "Fischerport", Host = db.Users.FirstOrDefault(g => g.Email == "jacobs@yahoo.com"), WeekendPrice = 113.86m, WeekdayPrice = 76.66m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House"), PetsAllowed = true, FreeParking = false, CleaningFee = 27.87m, Bedrooms = 3, Bathrooms = 4, GuestsAllowed = 10, MinNightsForDiscount = 7, DiscountRate = 0.11m, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3037, ZipCode = "71770", State = StateAbbr.IN, Street = "41489 Roger Terrace", City = "Davisfort", Host = db.Users.FirstOrDefault(g => g.Email == "jacobs@yahoo.com"), WeekendPrice = 299.09m, WeekdayPrice = 177.37m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin"), PetsAllowed = true, FreeParking = true, CleaningFee = 23.78m, Bedrooms = 6, Bathrooms = 8, GuestsAllowed = 6, MinNightsForDiscount = 19, DiscountRate = 0.09m, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3038, ZipCode = "05147", State = StateAbbr.CO, Street = "014 Aaron Locks Suite 714", City = "Justinborough", Host = db.Users.FirstOrDefault(g => g.Email == "rankin@yahoo.com"), WeekendPrice = 158.42m, WeekdayPrice = 104.05m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Condo"), PetsAllowed = true, FreeParking = false, CleaningFee = 5.36m, Bedrooms = 2, Bathrooms = 2, GuestsAllowed = 5, MinNightsForDiscount = 30, DiscountRate = 0.23m, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3039, ZipCode = "28062", State = StateAbbr.SC, Street = "8518 Pamela Track Apt. 164", City = "Aprilshire", Host = db.Users.FirstOrDefault(g => g.Email == "chung@yahoo.com"), WeekendPrice = 210.59m, WeekdayPrice = 199.37m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment"), PetsAllowed = false, FreeParking = true, CleaningFee = 8.83m, Bedrooms = 3, Bathrooms = 2, GuestsAllowed = 1, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3040, ZipCode = "88090", State = StateAbbr.OH, Street = "864 Ramos Port Apt. 211", City = "Moralesmouth", Host = db.Users.FirstOrDefault(g => g.Email == "tanner@utexas.edu"), WeekendPrice = 153.69m, WeekdayPrice = 94.48m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment"), PetsAllowed = true, FreeParking = true, CleaningFee = 16.85m, Bedrooms = 3, Bathrooms = 5, GuestsAllowed = 9, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3041, ZipCode = "28775", State = StateAbbr.RI, Street = "637 Neal Island Suite 074", City = "Lake Tyler", WeekendPrice = 196.14m, WeekdayPrice = 88.82m, PetsAllowed = true, FreeParking = false, CleaningFee = 6.97m, Bedrooms = 3, Bathrooms = 3, GuestsAllowed = 14, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "ingram@gmail.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Condo") },
                new Models.Property { PropertyId = 3042, ZipCode = "75585", State = StateAbbr.WV, Street = "0811 Smith Canyon Apt. 904", City = "Jessicabury", WeekendPrice = 123.22m, WeekdayPrice = 119.58m, PetsAllowed = false, FreeParking = true, CleaningFee = 18.45m, Bedrooms = 3, Bathrooms = 5, GuestsAllowed = 2, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "rankin@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3043, ZipCode = "17438", State = StateAbbr.MD, Street = "7562 Fisher Spur", City = "Hernandezberg", WeekendPrice = 283.77m, WeekdayPrice = 218.87m, PetsAllowed = false, FreeParking = false, CleaningFee = 19.07m, Bedrooms = 1, Bathrooms = 2, GuestsAllowed = 2, MinNightsForDiscount = 4, DiscountRate = 0.09m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "rice@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3044, ZipCode = "07027", State = StateAbbr.VT, Street = "5667 Blair Underpass", City = "South Shelby", WeekendPrice = 239.76m, WeekdayPrice = 76.19m, PetsAllowed = false, FreeParking = true, CleaningFee = 11.37m, Bedrooms = 2, Bathrooms = 4, GuestsAllowed = 13, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "morales@aol.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3045, ZipCode = "01008", State = StateAbbr.MI, Street = "6708 Carpenter Overpass Suite 735", City = "Bobbyton", WeekendPrice = 229.04m, WeekdayPrice = 161.17m, PetsAllowed = false, FreeParking = false, CleaningFee = 25.01m, Bedrooms = 7, Bathrooms = 7, GuestsAllowed = 7, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "rice@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Hotel") },
                new Models.Property { PropertyId = 3046, ZipCode = "60236", State = StateAbbr.ND, Street = "16396 Shawn Junction", City = "New Nicolemouth", WeekendPrice = 220.69m, WeekdayPrice = 106.06m, PetsAllowed = true, FreeParking = true, CleaningFee = 11.82m, Bedrooms = 4, Bathrooms = 4, GuestsAllowed = 6, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "rice@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3047, ZipCode = "01707", State = StateAbbr.CA, Street = "4486 Olson Well", City = "North Kevin", WeekendPrice = 138.96m, WeekdayPrice = 151.44m, PetsAllowed = false, FreeParking = false, CleaningFee = 6.72m, Bedrooms = 7, Bathrooms = 7, GuestsAllowed = 10, MinNightsForDiscount = 2, DiscountRate = 0.18m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "martinez@aol.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3048, ZipCode = "33233", State = StateAbbr.HI, Street = "67771 Christopher Courts Apt. 637", City = "Port Ronaldfurt", WeekendPrice = 134.28m, WeekdayPrice = 102.43m, PetsAllowed = false, FreeParking = false, CleaningFee = 19.81m, Bedrooms = 5, Bathrooms = 5, GuestsAllowed = 2, MinNightsForDiscount = 1, DiscountRate = 0.15m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "ingram@gmail.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3049, ZipCode = "79756", State = StateAbbr.NY, Street = "5561 Bishop Turnpike", City = "Lake Kenneth", WeekendPrice = 259.87m, WeekdayPrice = 94.31m, PetsAllowed = true, FreeParking = true, CleaningFee = 22.33m, Bedrooms = 5, Bathrooms = 7, GuestsAllowed = 11, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "gonzalez@aol.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3050, ZipCode = "36216", State = StateAbbr.SD, Street = "3019 Gerald Mall Apt. 340", City = "Trevinoville", WeekendPrice = 263.32m, WeekdayPrice = 151.69m, PetsAllowed = true, FreeParking = true, CleaningFee = 13.27m, Bedrooms = 5, Bathrooms = 5, GuestsAllowed = 1, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "chung@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3051, ZipCode = "43477", State = StateAbbr.NY, Street = "84331 Leonard Fort Suite 749", City = "East Lisa", WeekendPrice = 204.28m, WeekdayPrice = 204.04m, PetsAllowed = false, FreeParking = true, CleaningFee = 11.07m, Bedrooms = 7, Bathrooms = 8, GuestsAllowed = 10, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "chung@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Condo") },
                new Models.Property { PropertyId = 3052, ZipCode = "17819", State = StateAbbr.VA, Street = "62281 Kathy Tunnel", City = "Hudsonborough", WeekendPrice = 224.19m, WeekdayPrice = 165.51m, PetsAllowed = true, FreeParking = true, CleaningFee = 24.26m, Bedrooms = 1, Bathrooms = 1, GuestsAllowed = 9, MinNightsForDiscount = 5, DiscountRate = 0.12m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "ingram@gmail.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3053, ZipCode = "97149", State = StateAbbr.NM, Street = "9927 Christina Burg Suite 774", City = "East Angelaburgh", WeekendPrice = 121.74m, WeekdayPrice = 106.87m, PetsAllowed = false, FreeParking = false, CleaningFee = 5.62m, Bedrooms = 7, Bathrooms = 9, GuestsAllowed = 6, MinNightsForDiscount = 5, DiscountRate = 0.06m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "jacobs@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Condo") },
                new Models.Property { PropertyId = 3054, ZipCode = "45480", State = StateAbbr.IA, Street = "142 Warner View Suite 460", City = "North Leslie", WeekendPrice = 148.76m, WeekdayPrice = 212.32m, PetsAllowed = false, FreeParking = true, CleaningFee = 20.2m, Bedrooms = 5, Bathrooms = 7, GuestsAllowed = 9, MinNightsForDiscount = 41, DiscountRate = 0.12m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "ingram@gmail.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Hotel") },
                new Models.Property { PropertyId = 3055, ZipCode = "03720", State = StateAbbr.AR, Street = "5240 Berry Centers", City = "West Andrew", WeekendPrice = 111.01m, WeekdayPrice = 164.02m, PetsAllowed = true, FreeParking = true, CleaningFee = 26.21m, Bedrooms = 7, Bathrooms = 6, GuestsAllowed = 12, PropertyStatus = PropStatus.Unapproved, Host = db.Users.FirstOrDefault(g => g.Email == "rankin@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3056, ZipCode = "85576", State = StateAbbr.HI, Street = "51056 Patricia Forge", City = "Grahamstad", WeekendPrice = 167.53m, WeekdayPrice = 117.45m, PetsAllowed = true, FreeParking = true, CleaningFee = 24.75m, Bedrooms = 7, Bathrooms = 9, GuestsAllowed = 10, MinNightsForDiscount = 8, DiscountRate = 0.17m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "loter@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3057, ZipCode = "92199", State = StateAbbr.VA, Street = "0648 Malone Port Apt. 662", City = "New Devonhaven", WeekendPrice = 176.53m, WeekdayPrice = 209.47m, PetsAllowed = true, FreeParking = true, CleaningFee = 5.83m, Bedrooms = 6, Bathrooms = 5, GuestsAllowed = 12, MinNightsForDiscount = 3, DiscountRate = 0.05m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "gonzalez@aol.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3058, ZipCode = "05261", State = StateAbbr.SC, Street = "23028 Jennifer Meadow Apt. 972", City = "West Matthewfurt", WeekendPrice = 199.1m, WeekdayPrice = 153.04m, PetsAllowed = true, FreeParking = false, CleaningFee = 18.62m, Bedrooms = 1, Bathrooms = 2, GuestsAllowed = 14, MinNightsForDiscount = 19, DiscountRate = 0.13m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "ingram@gmail.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3059, ZipCode = "72649", State = StateAbbr.LA, Street = "2738 Martin Terrace Suite 547", City = "Smithhaven", WeekendPrice = 199.22m, WeekdayPrice = 196.56m, PetsAllowed = false, FreeParking = true, CleaningFee = 20.71m, Bedrooms = 1, Bathrooms = 1, GuestsAllowed = 11, MinNightsForDiscount = 4, DiscountRate = 0.14m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "tanner@utexas.edu"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Condo") },
                new Models.Property { PropertyId = 3060, ZipCode = "97488", State = StateAbbr.KY, Street = "984 Stephen Stravenue", City = "South Michaelton", WeekendPrice = 178.29m, WeekdayPrice = 117.03m, PetsAllowed = false, FreeParking = true, CleaningFee = 6.47m, Bedrooms = 4, Bathrooms = 6, GuestsAllowed = 3, MinNightsForDiscount = 4, DiscountRate = 0.05m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "ingram@gmail.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3061, ZipCode = "42837", State = StateAbbr.LA, Street = "98522 Mathis Viaduct Apt. 909", City = "West Michael", WeekendPrice = 252.79m, WeekdayPrice = 133.35m, PetsAllowed = false, FreeParking = false, CleaningFee = 9.15m, Bedrooms = 4, Bathrooms = 4, GuestsAllowed = 1, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "jacobs@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3062, ZipCode = "56059", State = StateAbbr.OH, Street = "620 Ashley Mills Apt. 507", City = "Julieborough", WeekendPrice = 296.05m, WeekdayPrice = 171.15m, PetsAllowed = false, FreeParking = true, CleaningFee = 18.26m, Bedrooms = 1, Bathrooms = 3, GuestsAllowed = 9, MinNightsForDiscount = 4, DiscountRate = 0.21m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "jacobs@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3063, ZipCode = "02288", State = StateAbbr.LA, Street = "212 Shelly Roads", City = "Fischerview", WeekendPrice = 163.88m, WeekdayPrice = 132.81m, PetsAllowed = false, FreeParking = true, CleaningFee = 7.46m, Bedrooms = 5, Bathrooms = 7, GuestsAllowed = 10, MinNightsForDiscount = 6, DiscountRate = 0.17m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "chung@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3064, ZipCode = "50851", State = StateAbbr.OK, Street = "8885 Lee Tunnel Suite 208", City = "Port Donna", WeekendPrice = 140.73m, WeekdayPrice = 228.84m, PetsAllowed = true, FreeParking = true, CleaningFee = 17.13m, Bedrooms = 7, Bathrooms = 7, GuestsAllowed = 7, MinNightsForDiscount = 22, DiscountRate = 0.23m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "chung@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Hotel") },
                new Models.Property { PropertyId = 3065, ZipCode = "03009", State = StateAbbr.NM, Street = "693 Michael Estate", City = "Lake Michael", WeekendPrice = 139.83m, WeekdayPrice = 155.03m, PetsAllowed = false, FreeParking = true, CleaningFee = 21.05m, Bedrooms = 4, Bathrooms = 5, GuestsAllowed = 13, MinNightsForDiscount = 21, DiscountRate = 0.09m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "tanner@utexas.edu"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3066, ZipCode = "92905", State = StateAbbr.NY, Street = "342 Miller Mission", City = "Lake Jennifer", WeekendPrice = 249.24m, WeekdayPrice = 128.41m, PetsAllowed = true, FreeParking = false, CleaningFee = 6.63m, Bedrooms = 4, Bathrooms = 5, GuestsAllowed = 1, MinNightsForDiscount = 8, DiscountRate = 0.07m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "martinez@aol.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3067, ZipCode = "65056", State = StateAbbr.AK, Street = "71664 Kim Throughway", City = "Chelsealand", WeekendPrice = 286.53m, WeekdayPrice = 163.68m, PetsAllowed = false, FreeParking = false, CleaningFee = 25.57m, Bedrooms = 6, Bathrooms = 8, GuestsAllowed = 9, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "rankin@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3068, ZipCode = "11181", State = StateAbbr.AZ, Street = "66660 Gomez Port Apt. 945", City = "South Thomashaven", WeekendPrice = 137.17m, WeekdayPrice = 93.86m, PetsAllowed = false, FreeParking = true, CleaningFee = 28.18m, Bedrooms = 4, Bathrooms = 3, GuestsAllowed = 2, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "tanner@utexas.edu"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3069, ZipCode = "53480", State = StateAbbr.FL, Street = "0131 Williams Ville Apt. 562", City = "Richardberg", WeekendPrice = 120.61m, WeekdayPrice = 86.25m, PetsAllowed = false, FreeParking = true, CleaningFee = 11.39m, Bedrooms = 6, Bathrooms = 5, GuestsAllowed = 13, MinNightsForDiscount = 10, DiscountRate = 0.17m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "loter@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3070, ZipCode = "11353", State = StateAbbr.OR, Street = "22708 Madison Spurs", City = "Herringstad", WeekendPrice = 241.25m, WeekdayPrice = 182.46m, PetsAllowed = false, FreeParking = false, CleaningFee = 18.29m, Bedrooms = 6, Bathrooms = 7, GuestsAllowed = 2, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "morales@aol.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3071, ZipCode = "05560", State = StateAbbr.FL, Street = "3454 Holmes Motorway", City = "Port Rachel", WeekendPrice = 123.04m, WeekdayPrice = 89.88m, PetsAllowed = true, FreeParking = false, CleaningFee = 19.14m, Bedrooms = 3, Bathrooms = 3, GuestsAllowed = 1, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "chung@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3072, ZipCode = "93500", State = StateAbbr.GA, Street = "805 James Turnpike", City = "Carrmouth", WeekendPrice = 219.86m, WeekdayPrice = 81.55m, PetsAllowed = false, FreeParking = false, CleaningFee = 13.38m, Bedrooms = 6, Bathrooms = 5, GuestsAllowed = 12, MinNightsForDiscount = 2, DiscountRate = 0.22m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "martinez@aol.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3073, ZipCode = "44515", State = StateAbbr.NV, Street = "8081 Smith Trail", City = "North Ronaldstad", WeekendPrice = 196.09m, WeekdayPrice = 130.47m, PetsAllowed = true, FreeParking = true, CleaningFee = 14.53m, Bedrooms = 7, Bathrooms = 7, GuestsAllowed = 3, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "jacobs@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3074, ZipCode = "07347", State = StateAbbr.MS, Street = "125 Ian Crossroad Apt. 593", City = "South Deannaport", WeekendPrice = 136.82m, WeekdayPrice = 148.1m, PetsAllowed = false, FreeParking = true, CleaningFee = 15.57m, Bedrooms = 2, Bathrooms = 1, GuestsAllowed = 4, MinNightsForDiscount = 22, DiscountRate = 0.22m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "morales@aol.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3075, ZipCode = "54532", State = StateAbbr.NH, Street = "1607 Munoz River", City = "Emilyshire", WeekendPrice = 209.77m, WeekdayPrice = 147.55m, PetsAllowed = false, FreeParking = true, CleaningFee = 27.65m, Bedrooms = 6, Bathrooms = 7, GuestsAllowed = 3, MinNightsForDiscount = 6, DiscountRate = 0.09m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "chung@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3076, ZipCode = "65516", State = StateAbbr.UT, Street = "3615 David Keys Apt. 269", City = "West Stephenside", WeekendPrice = 126.47m, WeekdayPrice = 86.8m, PetsAllowed = true, FreeParking = true, CleaningFee = 17.6m, Bedrooms = 2, Bathrooms = 4, GuestsAllowed = 3, MinNightsForDiscount = 21, DiscountRate = 0.06m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "gonzalez@aol.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3077, ZipCode = "20721", State = StateAbbr.AZ, Street = "640 Mary Common", City = "Michaelville", WeekendPrice = 173.01m, WeekdayPrice = 121.75m, PetsAllowed = false, FreeParking = true, CleaningFee = 12.53m, Bedrooms = 3, Bathrooms = 4, GuestsAllowed = 7, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "ingram@gmail.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3078, ZipCode = "43567", State = StateAbbr.LA, Street = "395 Timothy Road", City = "Williamsbury", WeekendPrice = 198.1m, WeekdayPrice = 160.23m, PetsAllowed = true, FreeParking = true, CleaningFee = 10.82m, Bedrooms = 5, Bathrooms = 7, GuestsAllowed = 5, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "loter@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3079, ZipCode = "01239", State = StateAbbr.OR, Street = "3267 Walter Dam", City = "Cunninghamtown", WeekendPrice = 127.7m, WeekdayPrice = 110.64m, PetsAllowed = true, FreeParking = false, CleaningFee = 26.67m, Bedrooms = 1, Bathrooms = 2, GuestsAllowed = 7, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "chung@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3080, ZipCode = "03966", State = StateAbbr.MS, Street = "00580 Brandon Creek", City = "Port Eric", WeekendPrice = 236.71m, WeekdayPrice = 227.6m, PetsAllowed = false, FreeParking = false, CleaningFee = 20.22m, Bedrooms = 3, Bathrooms = 5, GuestsAllowed = 2, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "jacobs@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3081, ZipCode = "29996", State = StateAbbr.MS, Street = "325 Amanda Cliffs Apt. 695", City = "South Paulabury", WeekendPrice = 135.59m, WeekdayPrice = 115.37m, PetsAllowed = false, FreeParking = true, CleaningFee = 29.8m, Bedrooms = 6, Bathrooms = 6, GuestsAllowed = 13, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "ingram@gmail.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3082, ZipCode = "93980", State = StateAbbr.CT, Street = "40956 Amanda Walk Apt. 260", City = "Simonfurt", WeekendPrice = 271.49m, WeekdayPrice = 93.35m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment"), PetsAllowed = false, FreeParking = false, CleaningFee = 8.54m, Bedrooms = 4, Bathrooms = 4, GuestsAllowed = 5, MinNightsForDiscount = 6, DiscountRate = 0.18m, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3083, ZipCode = "23687", State = StateAbbr.KS, Street = "25762 Gill Creek Suite 525", City = "Mccoyton", WeekendPrice = 247.15m, WeekdayPrice = 171.37m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Condo"), PetsAllowed = false, FreeParking = false, CleaningFee = 17.22m, Bedrooms = 1, Bathrooms = 3, GuestsAllowed = 5, MinNightsForDiscount = 8, DiscountRate = 0.21m, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3084, ZipCode = "04593", State = StateAbbr.GA, Street = "6048 Johnson Loop Suite 635", City = "East Daniel", WeekendPrice = 299.6m, WeekdayPrice = 95.59m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Condo"), PetsAllowed = true, FreeParking = true, CleaningFee = 24.3m, Bedrooms = 1, Bathrooms = 3, GuestsAllowed = 8, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3085, ZipCode = "96954", State = StateAbbr.RI, Street = "1168 Gary Fords Apt. 308", City = "Port Trevor", WeekendPrice = 278.17m, WeekdayPrice = 194.84m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment"), PetsAllowed = false, FreeParking = false, CleaningFee = 5.88m, Bedrooms = 1, Bathrooms = 2, GuestsAllowed = 11, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3086, ZipCode = "62271", State = StateAbbr.MS, Street = "164 Matthew Parkway Suite 826", City = "Jimmyfurt", WeekendPrice = 100.08m, WeekdayPrice = 112.03m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Condo"), PetsAllowed = true, FreeParking = true, CleaningFee = 28.82m, Bedrooms = 6, Bathrooms = 8, GuestsAllowed = 8, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3087, ZipCode = "05222", State = StateAbbr.CO, Street = "1220 Heidi Rue Apt. 998", City = "West Haleyburgh", WeekendPrice = 182.77m, WeekdayPrice = 127.97m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment"), PetsAllowed = false, FreeParking = true, CleaningFee = 13.02m, Bedrooms = 5, Bathrooms = 4, GuestsAllowed = 1, MinNightsForDiscount = 37, DiscountRate = 0.17m, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3088, ZipCode = "22365", State = StateAbbr.SD, Street = "751 Wood Square Suite 732", City = "Port Melissaburgh", WeekendPrice = 186.01m, WeekdayPrice = 120.07m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Hotel"), PetsAllowed = false, FreeParking = false, CleaningFee = 26.71m, Bedrooms = 7, Bathrooms = 7, GuestsAllowed = 13, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3089, ZipCode = "53609", State = StateAbbr.OR, Street = "376 Smith Dale Suite 279", City = "South Sarahland", WeekendPrice = 122.31m, WeekdayPrice = 137.96m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Hotel"), PetsAllowed = false, FreeParking = false, CleaningFee = 26.29m, Bedrooms = 2, Bathrooms = 2, GuestsAllowed = 9, MinNightsForDiscount = 29, DiscountRate = 0.10m, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3090, ZipCode = "09478", State = StateAbbr.CA, Street = "79148 Pierce Lock Suite 423", City = "Erikberg", WeekendPrice = 234.61m, WeekdayPrice = 226.57m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Hotel"), PetsAllowed = true, FreeParking = false, CleaningFee = 16.41m, Bedrooms = 3, Bathrooms = 5, GuestsAllowed = 6, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3091, ZipCode = "01425", State = StateAbbr.ID, Street = "147 Lisa Hill Apt. 512", City = "Port Elizabethshire", WeekendPrice = 145.15m, WeekdayPrice = 95.73m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment"), PetsAllowed = false, FreeParking = true, CleaningFee = 9.93m, Bedrooms = 4, Bathrooms = 6, GuestsAllowed = 10, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3092, ZipCode = "29941", State = StateAbbr.KY, Street = "971 Hansen Well Suite 103", City = "South Mary", WeekendPrice = 145.72m, WeekdayPrice = 161.68m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Hotel"), PetsAllowed = false, FreeParking = false, CleaningFee = 24.36m, Bedrooms = 6, Bathrooms = 8, GuestsAllowed = 4, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3093, ZipCode = "47577", State = StateAbbr.WY, Street = "511 Berry Fork Suite 623", City = "Sharonfort", WeekendPrice = 260.18m, WeekdayPrice = 183.81m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Hotel"), PetsAllowed = false, FreeParking = false, CleaningFee = 7.46m, Bedrooms = 4, Bathrooms = 5, GuestsAllowed = 3, PropertyStatus = PropStatus.Unapproved },
                new Models.Property { PropertyId = 3094, ZipCode = "94134", State = StateAbbr.WI, Street = "65873 Chen Knolls", City = "Ramirezfurt", WeekendPrice = 117.17m, WeekdayPrice = 215.38m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House"), PetsAllowed = false, FreeParking = false, CleaningFee = 24.31m, Bedrooms = 4, Bathrooms = 3, GuestsAllowed = 14, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3095, ZipCode = "57039", State = StateAbbr.IN, Street = "8799 Emma Parkway Suite 735", City = "North Thomasfurt", WeekendPrice = 242.21m, WeekdayPrice = 145.51m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Hotel"), PetsAllowed = false, FreeParking = false, CleaningFee = 11.89m, Bedrooms = 3, Bathrooms = 5, GuestsAllowed = 11, MinNightsForDiscount = 41, DiscountRate = 0.10m, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3096, ZipCode = "23718", State = StateAbbr.ND, Street = "30068 David View Apt. 173", City = "New Peggychester", WeekendPrice = 161.21m, WeekdayPrice = 142.76m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment"), PetsAllowed = false, FreeParking = true, CleaningFee = 20.92m, Bedrooms = 4, Bathrooms = 6, GuestsAllowed = 7, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3097, ZipCode = "26932", State = StateAbbr.MD, Street = "298 Johnathan Cove Apt. 402", City = "South Jamie", WeekendPrice = 176.37m, WeekdayPrice = 170.07m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment"), PetsAllowed = false, FreeParking = false, CleaningFee = 27.12m, Bedrooms = 4, Bathrooms = 5, GuestsAllowed = 14, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3098, ZipCode = "74554", State = StateAbbr.CO, Street = "171 Harrison Motorway", City = "Davidview", Host = db.Users.FirstOrDefault(g => g.Email == "chung@yahoo.com"), WeekendPrice = 234.81m, WeekdayPrice = 145.08m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House"), PetsAllowed = true, FreeParking = true, CleaningFee = 26.14m, Bedrooms = 6, Bathrooms = 8, GuestsAllowed = 10, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3099, ZipCode = "32097", State = StateAbbr.NE, Street = "3576 Sergio Avenue", City = "Benjaminmouth", Host = db.Users.FirstOrDefault(g => g.Email == "morales@aol.com"), WeekendPrice = 260.62m, WeekdayPrice = 111.73m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin"), PetsAllowed = false, FreeParking = false, CleaningFee = 15.89m, Bedrooms = 1, Bathrooms = 1, GuestsAllowed = 1, MinNightsForDiscount = 9, DiscountRate = 0.24m, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3100, ZipCode = "21519", State = StateAbbr.RI, Street = "37457 Tanya Pike Apt. 348", City = "North Ericton", Host = db.Users.FirstOrDefault(g => g.Email == "ingram@gmail.com"), WeekendPrice = 214.62m, WeekdayPrice = 70.63m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment"), PetsAllowed = false, FreeParking = true, CleaningFee = 5.29m, Bedrooms = 2, Bathrooms = 1, GuestsAllowed = 13, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3101, ZipCode = "76875", State = StateAbbr.PA, Street = "3673 Peter Turnpike Suite 835", City = "New Sandra", Host = db.Users.FirstOrDefault(g => g.Email == "loter@yahoo.com"), WeekendPrice = 172.79m, WeekdayPrice = 229.03m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Hotel"), PetsAllowed = false, FreeParking = true, CleaningFee = 14.05m, Bedrooms = 4, Bathrooms = 4, GuestsAllowed = 6, MinNightsForDiscount = 12, DiscountRate = 0.14m, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3102, ZipCode = "80451", State = StateAbbr.TX, Street = "939 Johnson Oval Suite 830", City = "North Dennismouth", Host = db.Users.FirstOrDefault(g => g.Email == "gonzalez@aol.com"), WeekendPrice = 133.53m, WeekdayPrice = 169.34m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Hotel"), PetsAllowed = false, FreeParking = true, CleaningFee = 18.06m, Bedrooms = 3, Bathrooms = 5, GuestsAllowed = 6, MinNightsForDiscount = 28, DiscountRate = 0.25m, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3103, ZipCode = "51726", State = StateAbbr.NV, Street = "645 Jennings Estates", City = "Angelastad", Host = db.Users.FirstOrDefault(g => g.Email == "tanner@utexas.edu"), WeekendPrice = 109.44m, WeekdayPrice = 155.52m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House"), PetsAllowed = false, FreeParking = false, CleaningFee = 8.28m, Bedrooms = 2, Bathrooms = 3, GuestsAllowed = 4, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3104, ZipCode = "77240", State = StateAbbr.MT, Street = "1231 Stephanie Lock Suite 835", City = "North Richardland", Host = db.Users.FirstOrDefault(g => g.Email == "martinez@aol.com"), WeekendPrice = 182.33m, WeekdayPrice = 180.2m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Hotel"), PetsAllowed = true, FreeParking = false, CleaningFee = 17.78m, Bedrooms = 5, Bathrooms = 7, GuestsAllowed = 5, MinNightsForDiscount = 13, DiscountRate = 0.13m, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3105, ZipCode = "98152", State = StateAbbr.CO, Street = "302 Parker Plains Apt. 197", City = "East Robertstad", Host = db.Users.FirstOrDefault(g => g.Email == "morales@aol.com"), WeekendPrice = 212.7m, WeekdayPrice = 212.86m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment"), PetsAllowed = true, FreeParking = false, CleaningFee = 6.82m, Bedrooms = 3, Bathrooms = 2, GuestsAllowed = 1, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3106, ZipCode = "98277", State = StateAbbr.MS, Street = "098 Hernandez Green", City = "New Sergiobury", Host = db.Users.FirstOrDefault(g => g.Email == "morales@aol.com"), WeekendPrice = 262.3m, WeekdayPrice = 188.71m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin"), PetsAllowed = false, FreeParking = true, CleaningFee = 21.88m, Bedrooms = 4, Bathrooms = 6, GuestsAllowed = 8, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3107, ZipCode = "80082", State = StateAbbr.NE, Street = "94102 Sims Port Suite 187", City = "Florestown", Host = db.Users.FirstOrDefault(g => g.Email == "rice@yahoo.com"), WeekendPrice = 128.05m, WeekdayPrice = 83.34m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Condo"), PetsAllowed = false, FreeParking = true, CleaningFee = 11.29m, Bedrooms = 4, Bathrooms = 4, GuestsAllowed = 8, MinNightsForDiscount = 8, DiscountRate = 0.21m, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3108, ZipCode = "71531", State = StateAbbr.ND, Street = "01630 Baker Crescent", City = "Kellyborough", Host = db.Users.FirstOrDefault(g => g.Email == "gonzalez@aol.com"), WeekendPrice = 125.27m, WeekdayPrice = 204.02m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin"), PetsAllowed = true, FreeParking = true, CleaningFee = 21.15m, Bedrooms = 1, Bathrooms = 1, GuestsAllowed = 4, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3109, ZipCode = "14157", State = StateAbbr.OK, Street = "70452 Forbes Courts", City = "Mosesland", Host = db.Users.FirstOrDefault(g => g.Email == "morales@aol.com"), WeekendPrice = 172.1m, WeekdayPrice = 90.98m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin"), PetsAllowed = true, FreeParking = false, CleaningFee = 18.09m, Bedrooms = 4, Bathrooms = 3, GuestsAllowed = 9, MinNightsForDiscount = 11, DiscountRate = 0.22m, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3110, ZipCode = "26899", State = StateAbbr.MO, Street = "0835 Angela Station", City = "East Heather", Host = db.Users.FirstOrDefault(g => g.Email == "tanner@utexas.edu"), WeekendPrice = 299.91m, WeekdayPrice = 158.64m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House"), PetsAllowed = true, FreeParking = false, CleaningFee = 23.09m, Bedrooms = 5, Bathrooms = 7, GuestsAllowed = 9, MinNightsForDiscount = 22, DiscountRate = 0.12m, PropertyStatus = PropStatus.Approved },
                new Models.Property { PropertyId = 3111, ZipCode = "42872", State = StateAbbr.VT, Street = "2458 Jason Village Suite 248", City = "North Donnamouth", WeekendPrice = 189.3m, WeekdayPrice = 107.97m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Condo"), PetsAllowed = false, FreeParking = true, CleaningFee = 9.05m, Bedrooms = 2, Bathrooms = 4, GuestsAllowed = 4, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "tanner@utexas.edu") },
                new Models.Property { PropertyId = 3112, ZipCode = "78301", State = StateAbbr.CO, Street = "1243 Grimes Corners", City = "Shawchester", WeekendPrice = 193.24m, WeekdayPrice = 214.14m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House"), PetsAllowed = true, FreeParking = true, CleaningFee = 26.1m, Bedrooms = 4, Bathrooms = 3, GuestsAllowed = 2, MinNightsForDiscount = 21, DiscountRate = 0.06m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "martinez@aol.com") },
                new Models.Property { PropertyId = 3113, ZipCode = "34523", State = StateAbbr.DC, Street = "558 Williams Station", City = "Port Pamela", WeekendPrice = 192.46m, WeekdayPrice = 106.3m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House"), PetsAllowed = false, FreeParking = true, CleaningFee = 17.59m, Bedrooms = 6, Bathrooms = 7, GuestsAllowed = 4, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "rankin@yahoo.com") },
                new Models.Property { PropertyId = 3114, ZipCode = "63064", State = StateAbbr.VT, Street = "4934 Lozano Place Suite 716", City = "Gavinton", WeekendPrice = 257.37m, WeekdayPrice = 116.99m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Hotel"), PetsAllowed = false, FreeParking = false, CleaningFee = 5.63m, Bedrooms = 5, Bathrooms = 6, GuestsAllowed = 6, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "chung@yahoo.com") },
                new Models.Property { PropertyId = 3115, ZipCode = "35700", State = StateAbbr.LA, Street = "41227 Patricia Lake", City = "Martinezbury", WeekendPrice = 108.28m, WeekdayPrice = 203.03m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House"), PetsAllowed = true, FreeParking = false, CleaningFee = 11.35m, Bedrooms = 2, Bathrooms = 1, GuestsAllowed = 3, MinNightsForDiscount = 4, DiscountRate = 0.10m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "gonzalez@aol.com") },
                new Models.Property { PropertyId = 3116, ZipCode = "55206", State = StateAbbr.VA, Street = "028 Harris Drive Apt. 422", City = "Amyburgh", WeekendPrice = 262.77m, WeekdayPrice = 163.3m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment"), PetsAllowed = true, FreeParking = true, CleaningFee = 13.74m, Bedrooms = 2, Bathrooms = 2, GuestsAllowed = 14, MinNightsForDiscount = 12, DiscountRate = 0.16m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "martinez@aol.com") },
                new Models.Property { PropertyId = 3117, ZipCode = "98240", State = StateAbbr.IA, Street = "06268 Lewis Place Suite 121", City = "Port Patriciatown", WeekendPrice = 108.52m, WeekdayPrice = 156.25m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Hotel"), PetsAllowed = false, FreeParking = false, CleaningFee = 23.66m, Bedrooms = 3, Bathrooms = 2, GuestsAllowed = 4, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "gonzalez@aol.com") },
                new Models.Property { PropertyId = 3118, ZipCode = "87205", State = StateAbbr.WI, Street = "5641 Brenda Streets Apt. 008", City = "Lake Seanmouth", WeekendPrice = 153.42m, WeekdayPrice = 178.27m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment"), PetsAllowed = true, FreeParking = false, CleaningFee = 24.69m, Bedrooms = 5, Bathrooms = 6, GuestsAllowed = 12, MinNightsForDiscount = 23, DiscountRate = 0.06m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "rankin@yahoo.com") },
                new Models.Property { PropertyId = 3119, ZipCode = "58221", State = StateAbbr.ME, Street = "92555 Shaw Spurs Suite 207", City = "New Randy", WeekendPrice = 184.92m, WeekdayPrice = 92.51m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Hotel"), PetsAllowed = false, FreeParking = true, CleaningFee = 12.82m, Bedrooms = 7, Bathrooms = 8, GuestsAllowed = 13, MinNightsForDiscount = 3, DiscountRate = 0.12m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "rice@yahoo.com") },
                new Models.Property { PropertyId = 3120, ZipCode = "18885", State = StateAbbr.NY, Street = "559 Foster Locks Suite 933", City = "Robinsonhaven", WeekendPrice = 225.85m, WeekdayPrice = 224.62m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Condo"), PetsAllowed = false, FreeParking = false, CleaningFee = 17.9m, Bedrooms = 6, Bathrooms = 6, GuestsAllowed = 6, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "tanner@utexas.edu") },
                new Models.Property { PropertyId = 3121, ZipCode = "00638", State = StateAbbr.WY, Street = "4647 Kristine Fields Suite 710", City = "New Dakota", WeekendPrice = 174.02m, WeekdayPrice = 112.61m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Condo"), PetsAllowed = true, FreeParking = false, CleaningFee = 17.48m, Bedrooms = 1, Bathrooms = 2, GuestsAllowed = 10, MinNightsForDiscount = 5, DiscountRate = 0.08m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "morales@aol.com") },
                new Models.Property { PropertyId = 3122, ZipCode = "31451", State = StateAbbr.ME, Street = "92594 Emily Shoals", City = "North Cathyburgh", WeekendPrice = 119.06m, WeekdayPrice = 189.98m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House"), PetsAllowed = false, FreeParking = false, CleaningFee = 25.11m, Bedrooms = 6, Bathrooms = 5, GuestsAllowed = 1, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "rankin@yahoo.com") },
                new Models.Property { PropertyId = 3123, ZipCode = "26297", State = StateAbbr.MS, Street = "551 Casey Squares Apt. 209", City = "Michaelborough", WeekendPrice = 114.73m, WeekdayPrice = 72.03m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment"), PetsAllowed = false, FreeParking = true, CleaningFee = 18.38m, Bedrooms = 1, Bathrooms = 1, GuestsAllowed = 6, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "martinez@aol.com") },
                new Models.Property { PropertyId = 3124, ZipCode = "04610", State = StateAbbr.PA, Street = "2998 Willis Wall", City = "North Brian", WeekendPrice = 144.51m, WeekdayPrice = 216.21m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House"), PetsAllowed = false, FreeParking = false, CleaningFee = 10.81m, Bedrooms = 3, Bathrooms = 4, GuestsAllowed = 3, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "loter@yahoo.com") },
                new Models.Property { PropertyId = 3125, ZipCode = "86618", State = StateAbbr.MD, Street = "164 Schultz Road", City = "Lake Bryan", WeekendPrice = 233.9m, WeekdayPrice = 132.69m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House"), PetsAllowed = false, FreeParking = true, CleaningFee = 15.8m, Bedrooms = 5, Bathrooms = 7, GuestsAllowed = 13, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "chung@yahoo.com") },
                new Models.Property { PropertyId = 3126, ZipCode = "80124", State = StateAbbr.GA, Street = "9541 Brock Estate Apt. 848", City = "Franklinchester", WeekendPrice = 285.05m, WeekdayPrice = 220.97m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment"), PetsAllowed = false, FreeParking = false, CleaningFee = 20.98m, Bedrooms = 2, Bathrooms = 1, GuestsAllowed = 9, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "jacobs@yahoo.com") },
                new Models.Property { PropertyId = 3127, ZipCode = "63590", State = StateAbbr.MS, Street = "588 Alan Rest", City = "Port Stephanieville", WeekendPrice = 180.86m, WeekdayPrice = 224.98m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House"), PetsAllowed = true, FreeParking = true, CleaningFee = 11.91m, Bedrooms = 6, Bathrooms = 6, GuestsAllowed = 12, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "ingram@gmail.com") },
                new Models.Property { PropertyId = 3128, ZipCode = "53548", State = StateAbbr.MT, Street = "216 Brandon Loop Apt. 096", City = "New Jessica", WeekendPrice = 239.97m, WeekdayPrice = 221.98m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment"), PetsAllowed = true, FreeParking = true, CleaningFee = 9.24m, Bedrooms = 5, Bathrooms = 7, GuestsAllowed = 12, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "rice@yahoo.com") },
                new Models.Property { PropertyId = 3129, ZipCode = "35611", State = StateAbbr.LA, Street = "782 Dawn Radial", City = "Port Christopher", WeekendPrice = 297.25m, WeekdayPrice = 76.56m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin"), PetsAllowed = false, FreeParking = true, CleaningFee = 20.42m, Bedrooms = 1, Bathrooms = 3, GuestsAllowed = 1, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "ingram@gmail.com") },
                new Models.Property { PropertyId = 3130, ZipCode = "42879", State = StateAbbr.WA, Street = "008 Nancy Route Suite 228", City = "North Stephanie", WeekendPrice = 129.36m, WeekdayPrice = 128.71m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Condo"), PetsAllowed = true, FreeParking = false, CleaningFee = 23.76m, Bedrooms = 2, Bathrooms = 3, GuestsAllowed = 3, MinNightsForDiscount = 3, DiscountRate = 0.08m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "morales@aol.com") },
                new Models.Property { PropertyId = 3131, ZipCode = "71569", State = StateAbbr.MO, Street = "115 Jon Isle Suite 788", City = "North Lesliefurt", WeekendPrice = 210.63m, WeekdayPrice = 114.21m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Hotel"), PetsAllowed = false, FreeParking = true, CleaningFee = 21.08m, Bedrooms = 1, Bathrooms = 2, GuestsAllowed = 9, MinNightsForDiscount = 42, DiscountRate = 0.21m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "loter@yahoo.com") },
                new Models.Property { PropertyId = 3132, ZipCode = "87566", State = StateAbbr.DE, Street = "132 Poole Pass Suite 212", City = "North Patrick", WeekendPrice = 280.37m, WeekdayPrice = 146.82m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Hotel"), PetsAllowed = false, FreeParking = true, CleaningFee = 26.78m, Bedrooms = 5, Bathrooms = 6, GuestsAllowed = 11, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "tanner@utexas.edu") },
                new Models.Property { PropertyId = 3133, ZipCode = "67652", State = StateAbbr.WY, Street = "457 Vargas Island Suite 853", City = "Lake Patrickstad", WeekendPrice = 249.39m, WeekdayPrice = 134.72m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Hotel"), PetsAllowed = false, FreeParking = false, CleaningFee = 19.19m, Bedrooms = 4, Bathrooms = 3, GuestsAllowed = 1, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "jacobs@yahoo.com") },
                new Models.Property { PropertyId = 3134, ZipCode = "45184", State = StateAbbr.HI, Street = "1569 Amy Path", City = "North Ashleyton", WeekendPrice = 111.23m, WeekdayPrice = 111.6m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin"), PetsAllowed = true, FreeParking = true, CleaningFee = 13.48m, Bedrooms = 7, Bathrooms = 8, GuestsAllowed = 7, MinNightsForDiscount = 5, DiscountRate = 0.21m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "tanner@utexas.edu") },
                new Models.Property { PropertyId = 3135, ZipCode = "04078", State = StateAbbr.IL, Street = "0375 Sandra Trace Suite 826", City = "Gailshire", WeekendPrice = 168.47m, WeekdayPrice = 89m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Hotel"), PetsAllowed = true, FreeParking = false, CleaningFee = 14.93m, Bedrooms = 5, Bathrooms = 6, GuestsAllowed = 3, MinNightsForDiscount = 36, DiscountRate = 0.21m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "tanner@utexas.edu") },
                new Models.Property { PropertyId = 3136, ZipCode = "50437", State = StateAbbr.MN, Street = "759 Good Port", City = "New Russell", WeekendPrice = 208.35m, WeekdayPrice = 208.64m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House"), PetsAllowed = true, FreeParking = true, CleaningFee = 7.09m, Bedrooms = 5, Bathrooms = 5, GuestsAllowed = 6, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "ingram@gmail.com") },
                new Models.Property { PropertyId = 3137, ZipCode = "34147", State = StateAbbr.WV, Street = "3895 Allen Junction", City = "West John", WeekendPrice = 195.41m, WeekdayPrice = 172.51m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin"), PetsAllowed = false, FreeParking = false, CleaningFee = 21.53m, Bedrooms = 5, Bathrooms = 7, GuestsAllowed = 3, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "chung@yahoo.com") },
                new Models.Property { PropertyId = 3138, ZipCode = "36340", State = StateAbbr.MS, Street = "7329 Jacobs Station", City = "New Tylerborough", WeekendPrice = 146.12m, WeekdayPrice = 163.15m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House"), PetsAllowed = false, FreeParking = false, CleaningFee = 18.98m, Bedrooms = 1, Bathrooms = 3, GuestsAllowed = 8, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "jacobs@yahoo.com") },
                new Models.Property { PropertyId = 3139, ZipCode = "88806", State = StateAbbr.MD, Street = "5003 Cassandra Estates Suite 148", City = "Haleychester", WeekendPrice = 161.49m, WeekdayPrice = 81.5m, Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Hotel"), PetsAllowed = true, FreeParking = false, CleaningFee = 16.41m, Bedrooms = 7, Bathrooms = 7, GuestsAllowed = 9, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "tanner@utexas.edu") },
                new Models.Property { PropertyId = 3140, ZipCode = "76853", State = StateAbbr.TN, Street = "10524 Parker Mall Suite 531", City = "Port Courtneyhaven", WeekendPrice = 120.73m, WeekdayPrice = 177.94m, PetsAllowed = false, FreeParking = true, CleaningFee = 9.5m, Bedrooms = 5, Bathrooms = 7, GuestsAllowed = 13, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "ingram@gmail.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Hotel") },
                new Models.Property { PropertyId = 3141, ZipCode = "93533", State = StateAbbr.MO, Street = "300 Madison Stream", City = "Christophershire", WeekendPrice = 187.08m, WeekdayPrice = 121.01m, PetsAllowed = false, FreeParking = false, CleaningFee = 16.48m, Bedrooms = 3, Bathrooms = 4, GuestsAllowed = 6, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "loter@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3142, ZipCode = "96763", State = StateAbbr.FL, Street = "4229 Derrick Wells", City = "West Tyler", WeekendPrice = 241.45m, WeekdayPrice = 199.68m, PetsAllowed = true, FreeParking = false, CleaningFee = 25.94m, Bedrooms = 2, Bathrooms = 4, GuestsAllowed = 6, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "martinez@aol.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3143, ZipCode = "92174", State = StateAbbr.VA, Street = "26239 Michael Shoals", City = "Gregoryview", WeekendPrice = 111.91m, WeekdayPrice = 162.01m, PetsAllowed = true, FreeParking = true, CleaningFee = 14.35m, Bedrooms = 1, Bathrooms = 2, GuestsAllowed = 9, MinNightsForDiscount = 29, DiscountRate = 0.10m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "morales@aol.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3144, ZipCode = "88294", State = StateAbbr.IN, Street = "302 Joy Spring Apt. 622", City = "Ryanhaven", WeekendPrice = 163.73m, WeekdayPrice = 173.36m, PetsAllowed = false, FreeParking = true, CleaningFee = 25.35m, Bedrooms = 1, Bathrooms = 3, GuestsAllowed = 12, MinNightsForDiscount = 32, DiscountRate = 0.06m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "ingram@gmail.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3145, ZipCode = "23464", State = StateAbbr.CA, Street = "734 Craig Overpass Suite 589", City = "Jefferyside", WeekendPrice = 287.28m, WeekdayPrice = 216.10m, PetsAllowed = false, FreeParking = false, CleaningFee = 22.20m, Bedrooms = 1, Bathrooms = 3, GuestsAllowed = 8, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "martinez@aol.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Condo") },
                new Models.Property { PropertyId = 3146, ZipCode = "35243", State = StateAbbr.CA, Street = "272 Green Street", City = "Port Lacey", WeekendPrice = 247.34m, WeekdayPrice = 211.51m, PetsAllowed = true, FreeParking = false, CleaningFee = 11.73m, Bedrooms = 4, Bathrooms = 3, GuestsAllowed = 7, MinNightsForDiscount = 6, DiscountRate = 0.13m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "martinez@aol.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3147, ZipCode = "61935", State = StateAbbr.IL, Street = "8056 Dunn Trail Apt. 049", City = "Blackshire", WeekendPrice = 189.08m, WeekdayPrice = 111.40m, PetsAllowed = false, FreeParking = true, CleaningFee = 19.58m, Bedrooms = 5, Bathrooms = 6, GuestsAllowed = 2, MinNightsForDiscount = 9, DiscountRate = 0.07m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "loter@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3148, ZipCode = "72324", State = StateAbbr.CA, Street = "86187 Antonio Fort", City = "North Carmen", WeekendPrice = 109.87m, WeekdayPrice = 150.69m, PetsAllowed = true, FreeParking = false, CleaningFee = 13.30m, Bedrooms = 7, Bathrooms = 9, GuestsAllowed = 7, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "tanner@utexas.edu"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3149, ZipCode = "84393", State = StateAbbr.NJ, Street = "71318 Cassandra Plaza", City = "Burkeview", WeekendPrice = 227.55m, WeekdayPrice = 184.21m, PetsAllowed = true, FreeParking = false, CleaningFee = 19.52m, Bedrooms = 7, Bathrooms = 7, GuestsAllowed = 10, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "loter@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3150, ZipCode = "62346", State = StateAbbr.NH, Street = "5303 Lewis Springs", City = "Port Adrian", WeekendPrice = 207.51m, WeekdayPrice = 204.67m, PetsAllowed = false, FreeParking = false, CleaningFee = 26.36m, Bedrooms = 2, Bathrooms = 1, GuestsAllowed = 2, MinNightsForDiscount = 44, DiscountRate = 0.22m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "tanner@utexas.edu"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3151, ZipCode = "02837", State = StateAbbr.IA, Street = "465 Wiley Corners Apt. 759", City = "East Michellechester", WeekendPrice = 213.84m, WeekdayPrice = 129.14m, PetsAllowed = false, FreeParking = false, CleaningFee = 12.81m, Bedrooms = 6, Bathrooms = 5, GuestsAllowed = 11, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "gonzalez@aol.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3152, ZipCode = "68847", State = StateAbbr.LA, Street = "521 Flores Stream", City = "West Rebeccaborough", WeekendPrice = 254.37m, WeekdayPrice = 77.06m, PetsAllowed = true, FreeParking = true, CleaningFee = 6.03m, Bedrooms = 3, Bathrooms = 5, GuestsAllowed = 3, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "rankin@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3153, ZipCode = "35218", State = StateAbbr.NE, Street = "0271 Soto Drives Apt. 975", City = "New Edgar", WeekendPrice = 233.17m, WeekdayPrice = 179.91m, PetsAllowed = false, FreeParking = true, CleaningFee = 11.04m, Bedrooms = 4, Bathrooms = 5, GuestsAllowed = 9, MinNightsForDiscount = 32, DiscountRate = 0.18m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "tanner@utexas.edu"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3154, ZipCode = "32697", State = StateAbbr.NM, Street = "27862 Kent Mountains", City = "Lake Michaelville", WeekendPrice = 153.38m, WeekdayPrice = 90.54m, PetsAllowed = true, FreeParking = false, CleaningFee = 6.91m, Bedrooms = 6, Bathrooms = 5, GuestsAllowed = 14, MinNightsForDiscount = 30, DiscountRate = 0.18m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "jacobs@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3155, ZipCode = "95889", State = StateAbbr.OR, Street = "917 Mclaughlin Glens", City = "Martinville", WeekendPrice = 226.89m, WeekdayPrice = 225.59m, PetsAllowed = false, FreeParking = true, CleaningFee = 28.99m, Bedrooms = 7, Bathrooms = 6, GuestsAllowed = 2, MinNightsForDiscount = 15, DiscountRate = 0.12m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "rankin@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3156, ZipCode = "82153", State = StateAbbr.KY, Street = "3032 Michelle Drives", City = "North Daniel", WeekendPrice = 157.15m, WeekdayPrice = 203.25m, PetsAllowed = false, FreeParking = true, CleaningFee = 15.68m, Bedrooms = 3, Bathrooms = 4, GuestsAllowed = 13, MinNightsForDiscount = 9, DiscountRate = 0.23m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "rankin@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3157, ZipCode = "32202", State = StateAbbr.SD, Street = "601 Maria Mission Apt. 554", City = "Myerstown", WeekendPrice = 269.55m, WeekdayPrice = 223.27m, PetsAllowed = false, FreeParking = true, CleaningFee = 11.35m, Bedrooms = 7, Bathrooms = 9, GuestsAllowed = 9, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "tanner@utexas.edu"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3158, ZipCode = "17431", State = StateAbbr.OH, Street = "238 Shawn Well", City = "Port Johnshire", WeekendPrice = 112.64m, WeekdayPrice = 173.63m, PetsAllowed = true, FreeParking = true, CleaningFee = 6.38m, Bedrooms = 7, Bathrooms = 8, GuestsAllowed = 14, MinNightsForDiscount = 13, DiscountRate = 0.06m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "ingram@gmail.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3159, ZipCode = "37901", State = StateAbbr.SC, Street = "41743 Berger Inlet Apt. 527", City = "South Tammymouth", WeekendPrice = 163.20m, WeekdayPrice = 176.23m, PetsAllowed = true, FreeParking = false, CleaningFee = 14.77m, Bedrooms = 7, Bathrooms = 9, GuestsAllowed = 9, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "rice@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3160, ZipCode = "17895", State = StateAbbr.MO, Street = "9983 Mary Grove Apt. 643", City = "Beardview", WeekendPrice = 209.33m, WeekdayPrice = 219.53m, PetsAllowed = true, FreeParking = false, CleaningFee = 24.51m, Bedrooms = 7, Bathrooms = 6, GuestsAllowed = 9, MinNightsForDiscount = 16, DiscountRate = 0.10m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "ingram@gmail.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3161, ZipCode = "90576", State = StateAbbr.HI, Street = "03541 Ryan Islands Apt. 562", City = "East Michaelfort", WeekendPrice = 269.63m, WeekdayPrice = 126.25m, PetsAllowed = false, FreeParking = true, CleaningFee = 8.27m, Bedrooms = 1, Bathrooms = 2, GuestsAllowed = 10, MinNightsForDiscount = 8, DiscountRate = 0.16m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "rice@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3162, ZipCode = "94980", State = StateAbbr.SC, Street = "6591 Angela Mission Apt. 108", City = "Penabury", WeekendPrice = 286.86m, WeekdayPrice = 143.98m, PetsAllowed = false, FreeParking = true, CleaningFee = 20.48m, Bedrooms = 5, Bathrooms = 6, GuestsAllowed = 14, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "chung@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3163, ZipCode = "44974", State = StateAbbr.CO, Street = "492 Ramirez Crossing", City = "Aaronberg", WeekendPrice = 144.60m, WeekdayPrice = 121.91m, PetsAllowed = false, FreeParking = true, CleaningFee = 10.12m, Bedrooms = 1, Bathrooms = 2, GuestsAllowed = 10, MinNightsForDiscount = 8, DiscountRate = 0.22m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "rice@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3164, ZipCode = "66170", State = StateAbbr.DE, Street = "35974 Sharon Locks Apt. 101", City = "Jennyport", WeekendPrice = 114.46m, WeekdayPrice = 137.80m, PetsAllowed = true, FreeParking = false, CleaningFee = 17.74m, Bedrooms = 7, Bathrooms = 9, GuestsAllowed = 1, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "martinez@aol.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3165, ZipCode = "22495", State = StateAbbr.UT, Street = "89403 Gabriella Mills", City = "East Steven", WeekendPrice = 155.10m, WeekdayPrice = 128.63m, PetsAllowed = false, FreeParking = false, CleaningFee = 23.05m, Bedrooms = 3, Bathrooms = 4, GuestsAllowed = 11, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "gonzalez@aol.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3166, ZipCode = "85059", State = StateAbbr.NH, Street = "601 Kyle Roads", City = "Clarkfurt", WeekendPrice = 284.39m, WeekdayPrice = 209.11m, PetsAllowed = false, FreeParking = false, CleaningFee = 6.25m, Bedrooms = 4, Bathrooms = 5, GuestsAllowed = 4, MinNightsForDiscount = 6, DiscountRate = 0.14m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "tanner@utexas.edu"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3167, ZipCode = "61092", State = StateAbbr.IN, Street = "60969 Justin Passage Suite 774", City = "Joshuaburgh", WeekendPrice = 121.00m, WeekdayPrice = 128.59m, PetsAllowed = false, FreeParking = false, CleaningFee = 19.36m, Bedrooms = 1, Bathrooms = 1, GuestsAllowed = 7, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "loter@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Condo") },
                new Models.Property { PropertyId = 3168, ZipCode = "43986", State = StateAbbr.PA, Street = "7943 Tina Mount", City = "East Lisa", WeekendPrice = 104.47m, WeekdayPrice = 122.88m, PetsAllowed = true, FreeParking = true, CleaningFee = 25.31m, Bedrooms = 4, Bathrooms = 3, GuestsAllowed = 14, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "gonzalez@aol.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3169, ZipCode = "91397", State = StateAbbr.NC, Street = "6775 James Ford", City = "South Victorialand", WeekendPrice = 275.50m, WeekdayPrice = 211.24m, PetsAllowed = true, FreeParking = true, CleaningFee = 15.74m, Bedrooms = 1, Bathrooms = 3, GuestsAllowed = 9, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "jacobs@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3170, ZipCode = "67849", State = StateAbbr.VT, Street = "431 Johnson Neck Suite 039", City = "Mariechester", WeekendPrice = 126.24m, WeekdayPrice = 124.65m, PetsAllowed = true, FreeParking = false, CleaningFee = 24.30m, Bedrooms = 1, Bathrooms = 1, GuestsAllowed = 9, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "rice@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Condo") },
                new Models.Property { PropertyId = 3171, ZipCode = "20687", State = StateAbbr.NM, Street = "15666 Justin Locks", City = "Lake Ryanport", WeekendPrice = 112.05m, WeekdayPrice = 70.11m, PetsAllowed = false, FreeParking = false, CleaningFee = 27.45m, Bedrooms = 6, Bathrooms = 6, GuestsAllowed = 3, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "tanner@utexas.edu"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3172, ZipCode = "30222", State = StateAbbr.TX, Street = "9947 Torres Viaduct Apt. 506", City = "Benjaminport", WeekendPrice = 152.09m, WeekdayPrice = 174.87m, PetsAllowed = true, FreeParking = false, CleaningFee = 18.44m, Bedrooms = 1, Bathrooms = 2, GuestsAllowed = 11, MinNightsForDiscount = 8, DiscountRate = 0.08m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "ingram@gmail.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Apartment") },
                new Models.Property { PropertyId = 3173, ZipCode = "21190", State = StateAbbr.NJ, Street = "20866 Keith Mill", City = "Susanton", WeekendPrice = 174.06m, WeekdayPrice = 96.80m, PetsAllowed = false, FreeParking = false, CleaningFee = 28.15m, Bedrooms = 2, Bathrooms = 4, GuestsAllowed = 10, MinNightsForDiscount = 21, DiscountRate = 0.10m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "chung@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3174, ZipCode = "04838", State = StateAbbr.AL, Street = "04374 Nicholas Cliff Suite 001", City = "Adrianport", WeekendPrice = 108.24m, WeekdayPrice = 205.01m, PetsAllowed = true, FreeParking = false, CleaningFee = 6.56m, Bedrooms = 1, Bathrooms = 1, GuestsAllowed = 10, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "jacobs@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Condo") },
                new Models.Property { PropertyId = 3175, ZipCode = "80130", State = StateAbbr.CA, Street = "271 Andrew Summit", City = "Port Craig", WeekendPrice = 148.39m, WeekdayPrice = 197.52m, PetsAllowed = true, FreeParking = true, CleaningFee = 20.55m, Bedrooms = 7, Bathrooms = 6, GuestsAllowed = 7, MinNightsForDiscount = 27, DiscountRate = 0.14m, PropertyStatus = PropStatus.Unapproved, Host = db.Users.FirstOrDefault(g => g.Email == "gonzalez@aol.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3176, ZipCode = "96166", State = StateAbbr.MN, Street = "17611 Robbins Mission", City = "New Curtis", WeekendPrice = 286.13m, WeekdayPrice = 219.69m, PetsAllowed = true, FreeParking = false, CleaningFee = 10.64m, Bedrooms = 3, Bathrooms = 3, GuestsAllowed = 9, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "loter@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3177, ZipCode = "40702", State = StateAbbr.MO, Street = "80831 Kemp Pines", City = "Annashire", WeekendPrice = 123.93m, WeekdayPrice = 91.26m, PetsAllowed = true, FreeParking = true, CleaningFee = 19.36m, Bedrooms = 1, Bathrooms = 2, GuestsAllowed = 7, MinNightsForDiscount = 19, DiscountRate = 0.23m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "loter@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3178, ZipCode = "86023", State = StateAbbr.IL, Street = "96545 Smith Alley", City = "West Joy", WeekendPrice = 254.38m, WeekdayPrice = 132.54m, PetsAllowed = true, FreeParking = false, CleaningFee = 14.83m, Bedrooms = 6, Bathrooms = 8, GuestsAllowed = 7, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "martinez@aol.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3179, ZipCode = "70897", State = StateAbbr.MT, Street = "6146 Johnson Isle", City = "South Arthur", WeekendPrice = 228.04m, WeekdayPrice = 227.96m, PetsAllowed = true, FreeParking = true, CleaningFee = 6.99m, Bedrooms = 2, Bathrooms = 4, GuestsAllowed = 1, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "chung@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3180, ZipCode = "69154", State = StateAbbr.MN, Street = "0415 Smith Springs", City = "Jeremyburgh", WeekendPrice = 228.81m, WeekdayPrice = 140.93m, PetsAllowed = true, FreeParking = false, CleaningFee = 29.74m, Bedrooms = 4, Bathrooms = 4, GuestsAllowed = 3, MinNightsForDiscount = 21, DiscountRate = 0.15m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "loter@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3181, ZipCode = "53524", State = StateAbbr.HI, Street = "3999 Ricky Via", City = "West Adamburgh", WeekendPrice = 255.43m, WeekdayPrice = 137.35m, PetsAllowed = true, FreeParking = true, CleaningFee = 16.62m, Bedrooms = 7, Bathrooms = 6, GuestsAllowed = 6, MinNightsForDiscount = 21, DiscountRate = 0.14m, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "chung@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "House") },
                new Models.Property { PropertyId = 3182, ZipCode = "24886", State = StateAbbr.MN, Street = "83787 Stuart Key", City = "Davetown", WeekendPrice = 146.75m, WeekdayPrice = 172.99m, PetsAllowed = true, FreeParking = false, CleaningFee = 26.24m, Bedrooms = 7, Bathrooms = 6, GuestsAllowed = 4, MinNightsForDiscount = 6, DiscountRate = 0.23m, PropertyStatus = PropStatus.Unapproved, Host = db.Users.FirstOrDefault(g => g.Email == "chung@yahoo.com"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") },
                new Models.Property { PropertyId = 3183, ZipCode = "56713", State = StateAbbr.TX, Street = "690 Christina Park", City = "Toddburgh", WeekendPrice = 157.96m, WeekdayPrice = 188.53m, PetsAllowed = false, FreeParking = false, CleaningFee = 6.69m, Bedrooms = 3, Bathrooms = 5, GuestsAllowed = 1, PropertyStatus = PropStatus.Approved, Host = db.Users.FirstOrDefault(g => g.Email == "tanner@utexas.edu"), Category = db.Categories.FirstOrDefault(g => g.CategoryName == "Cabin") }


            };

            using (var transaction = db.Database.BeginTransaction())
            {
                try
                {
                    db.Database.ExecuteSqlRaw("SET IDENTITY_INSERT Properties ON");

                    // Fetch the Host
                    foreach(Models.Property property in Properties)
                    {
                        if (!db.Properties.Any(c => c.PropertyId == property.PropertyId))
                        {
                            db.Properties.Add(property);
                        }
                    }

                    db.SaveChanges();
                    db.Database.ExecuteSqlRaw("SET IDENTITY_INSERT Properties OFF");
                    transaction.Commit();

                    Console.WriteLine("Successfully seeded property with PropertyId = 3183.");
                }
                catch (Exception ex)
                {
                    transaction.Rollback();
                    Console.WriteLine("Error seeding property: " + ex.Message);
                    throw;
                }
            }
        }



        /*
        public static void SeedAllProperties(AppDbContext db)
        {
            // Retrieving properties from the database to associate them with unavailabilities
            var hosts = db.Users.ToList();
            var categories = db.Categories.ToList();


            List <Property> properties = new List<Property>
            {
                new Property { PropertyId = 3001, ZipCode = "72227", State = StateAbbr.PA, Street = "8714 Mann Plaza", City = "Lisaside",
                    WeekendPrice = 171.57m, WeekdayPrice = 152.68m, PetsAllowed = false, FreeParking = false, CleaningFee = 8.88m,
                    Bedrooms = 5, Bathrooms = 6, GuestsAllowed = 9, PropertyStatus = PropStatus.Approved,
                    Host = hosts.FirstOrDefault(h => h.Email == "gonzalez@aol.com"),
                    Category = categories.FirstOrDefault(c => c.CategoryName == "House") },
            };


            foreach (Property property in properties)
            {
                if (!db.Properties.Any(u => u.PropertyId == property.PropertyId))
                {
                    db.Properties.Add(property);
                }
            }


            db.SaveChanges();
            Console.WriteLine("Seeded all properties with navigational properties!");
        }
        */
    }
}

